// Node script to extract unique lowercase words from input.txt
// and emit output.js exporting the array.

const fs = require('fs');
const path = require('path');

const inputPath = path.join(__dirname, 'input.txt');
const outputPath = path.join(__dirname, 'output.js');

function extractUniqueWords(text) {
    const normalized = text
        .toLowerCase()
        .trim();
    if (!normalized) return [];
    const words = normalized
        .split(/\r?\n/) // handle Windows and Unix newlines
        .flatMap((line) => line.split(','))
        .map((s) => s.trim())
        .filter(Boolean);
    return Array.from(new Set(words)).sort();
}

function main() {
    const input = fs.readFileSync(inputPath, 'utf8');
    const uniqueWords = extractUniqueWords(input);
    const fileHeader = '// Auto-generated by generate-trait-words.js — do not edit manually\n';
    const exportContent = `export const TRAIT_WORDS = ${JSON.stringify(uniqueWords, null, 2)};\n`;
    fs.writeFileSync(outputPath, fileHeader + exportContent, 'utf8');
    console.log(`Wrote ${uniqueWords.length} unique words to ${path.relative(process.cwd(), outputPath)}`);
}

main();
